FROM node

MAINTAINER Yuthasak Tanruengsri<yuthasak.tanruengsri@gmail.de>

RUN mkdir -p /opt/sinopia/storage

WORKDIR /opt/sinopia

# Install sinopia and necessary tools
RUN npm install sinopia2 sinopia2-github-auth --production

# Set default registry to sinopia2
npm set registry http://localhost:4873/

# Copy config
ADD config.yaml /opt/sinopia/config.yaml

CMD ["/opt/sinopia/node_modules/sinopia/bin/sinopia"]

EXPOSE 4873

VOLUME /opt/sinopia/storage
